# -*- coding: utf-8 -*-
"""urduTokenizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gMoauTeRMhMZ6HhuKk-mqdC30OSOFL71
"""

!pip install transformers tokenizers

from tokenizers import Tokenizer
from tokenizers.models import BPE
tokenizer = Tokenizer(BPE(unk_token="[UNK]"))

from tokenizers.trainers import BpeTrainer
trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"])

from tokenizers.pre_tokenizers import Whitespace
tokenizer.pre_tokenizer = Whitespace()

files = [f"test.txt"]
tokenizer.train(files, trainer)

tokenizer.save("./unigram-tokenizer-urdu.json")

tokenizer = Tokenizer.from_file("./unigram-tokenizer-urdu.json")

output = tokenizer.encode("کیا حال ے؟")

print(output.tokens)

print(output.ids)

from tokenizers.processors import TemplateProcessing

tokenizer.post_processor = TemplateProcessing(
    single="[CLS] $A [SEP]",
    pair="[CLS] $A [SEP] $B:1 [SEP]:1",
    special_tokens=[
        ("[CLS]", tokenizer.token_to_id("[CLS]")),
        ("[SEP]", tokenizer.token_to_id("[SEP]")),
    ],
)

output = tokenizer.encode("تھیک ٹھاک")

print(output.tokens)